version: '3.7'

services:

  .server:
    container_name: server
    image: busybox
    deploy:
      resources:
        limits:
          cpus: "0.08"
          memory: "500MB"
    hostname: server
    extra_hosts:
      - "redis:172.16.0.5"
    depends_on:
      - redis

