name: Build Docker(s)

on:
  workflow_dispatch:
  push:
    paths:
      - go/**
      - nodejs/**
      - python/**
      - python-fastapi/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {target: "go", tag: "go-helloworld"}
          - {target: "python", tag: "python-helloworld"}
          - {target: "python-fastapi", tag: "fastapi-helloworld"}
          - {target: "nodejs", tag: "nodejs-helloworld"}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:${{ matrix.target }}"
        push: true
        tags: marcelndeffo/tests:${{ matrix.tag }}
